/**
 * Cookie Netscape 格式转换工具
 *
 * 将 CookieCloud 返回的 JSON 格式 cookie 转换为 Netscape 格式
 * 供 yt-dlp 等工具使用
 */

import fs from 'fs';
import path from 'path';
import logger from './logger.js';

/**
 * 将 cookie 字符串转换为 Netscape 格式
 * @param {string} cookieString - cookie 字符串，格式如 "name1=value1; name2=value2"
 * @param {string} domain - 域名，如 ".youtube.com"
 * @returns {string} Netscape 格式的 cookie 文件内容
 */
export function cookieStringToNetscape(cookieString, domain = '.youtube.com') {
  const lines = ['# Netscape HTTP Cookie File', '# Generated by bilibili-history-server', ''];

  if (!cookieString) {
    return lines.join('\n');
  }

  // 解析 cookie 字符串
  const cookies = cookieString.split(';').map(c => c.trim()).filter(c => c);

  for (const cookie of cookies) {
    const [name, ...valueParts] = cookie.split('=');
    const value = valueParts.join('='); // 处理 value 中包含 = 的情况

    if (!name || value === undefined) {
      continue;
    }

    // Netscape 格式：domain, includeSubdomains, path, secure, expires, name, value
    // 默认值：includeSubdomains=TRUE, path=/, secure=TRUE, expires=0 (session)
    const includeSubdomains = domain.startsWith('.') ? 'TRUE' : 'FALSE';
    const isSecure = name.startsWith('__Secure-') ? 'TRUE' : 'FALSE';
    const expires = '0'; // Session cookie

    lines.push(`${domain}\t${includeSubdomains}\t/\t${isSecure}\t${expires}\t${name.trim()}\t${value.trim()}`);
  }

  return lines.join('\n') + '\n';
}

/**
 * 将 cookie 字符串写入 Netscape 格式文件
 * @param {string} cookieString - cookie 字符串
 * @param {string} filePath - 输出文件路径
 * @param {string} domain - 域名
 * @returns {Promise<string>} 写入的文件路径
 */
export async function writeCookieNetscapeFile(cookieString, filePath, domain = '.youtube.com') {
  const content = cookieStringToNetscape(cookieString, domain);

  // 确保目录存在
  const dir = path.dirname(filePath);
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }

  fs.writeFileSync(filePath, content, 'utf-8');
  logger.debug(`[CookieNetscape] Cookie 文件已写入: ${filePath}`);

  return filePath;
}

/**
 * 删除临时 cookie 文件
 * @param {string} filePath - 文件路径
 */
export function removeCookieFile(filePath) {
  try {
    if (fs.existsSync(filePath)) {
      fs.unlinkSync(filePath);
      logger.debug(`[CookieNetscape] Cookie 文件已删除: ${filePath}`);
    }
  } catch (err) {
    logger.warn(`[CookieNetscape] 删除 cookie 文件失败: ${err.message}`);
  }
}

export default {
  cookieStringToNetscape,
  writeCookieNetscapeFile,
  removeCookieFile,
};
